### ISSUE TITLE
Groom README.md

### ISSUE THREAD

**Issue by gsmachado** [AxLabs/neofs-shared-lib#12]
- Key functions exported by the shared library (i.e., public functions to be used)
- Describe how the dynamics of the shared library (e.g., explain the UUIDs returned by the createClient() and things like this)
- Other key info on how to use the lib API

**Comment by gsmachado** [comment]
@mialbu this also, it would be nice to achieve soon. Then we get one step further to announce neofs-shared-lib.

**Comment by mialbu** [comment]
This has been done in the commits bcdc39850891dc7961f42e4d5e7a5d97484b0f3f and 8b37979aba5f9c34bf1cbb5237e3bc48b6574690.
