### ISSUE TITLE
Test shared lib for different platforms (Round 1)

### ISSUE THREAD

**Issue by gsmachado** [AxLabs/neofs-shared-lib#13]
We should test whether the .so and .h files generated for windows/amd64 (and other platforms) are actually working. 🤔

**Comment by gsmachado** [comment]
@mialbu this would be good to achieve soon.

**Comment by mialbu** [comment]
@gsmachado Can you create a list here of what you could test successfully and what is still todo?

**Comment by gsmachado** [comment]
@mialbu yes, I'm creating a list of it.

**Comment by gsmachado** [comment]
@mialbu added the results on `develop` branch, in this commit:
https://github.com/AxLabs/neofs-shared-lib/commit/15c21cb3b02034475982a5f46446bc36ec8b4b07

**Comment by gsmachado** [comment]
I will create a follow-up issue for tests... like a "round 2".

**Comment by gsmachado** [comment]
Closing for now!
